=== takacsakos12/VTJ4ESWebXML/VTJ4ES_1008/VTJ4ES_orarend.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="VTJ4ES_orarend" type="orarendType"/>

  <xs:complexType name="orarendType">
    <xs:sequence>
      <xs:element name="ora" type="oraType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="oraType">
    <xs:sequence>
      <xs:element name="targy" type="xs:string"/>
      <xs:element name="idopont" type="idopontType"/>
      <xs:element name="helyszin" type="xs:string"/>
      <xs:element name="oktato" type="xs:string"/>
      <xs:element name="szak" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
    <xs:attribute name="tipus" type="tipusType" use="required"/>
  </xs:complexType>

  <xs:complexType name="idopontType">
    <xs:sequence>
      <xs:element name="nap" type="napType"/>
      <xs:element name="tol" type="timeHHMMType"/>
      <xs:element name="ig" type="timeHHMMType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="napType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Hétfő"/>
      <xs:enumeration value="Kedd"/>
      <xs:enumeration value="Szerda"/>
      <xs:enumeration value="Csütörtök"/>
      <xs:enumeration value="Péntek"/>
      <xs:enumeration value="Szombat"/>
      <xs:enumeration value="Vasárnap"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="timeHHMMType">
    <xs:restriction base="xs:string">
      <xs:pattern value="^([01]\d|2[0-3]):[0-5]\d$"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipusType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="elmelet"/>
      <xs:enumeration value="elmélet"/>
      <xs:enumeration value="gyakorlat"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== takacsakos12/VTJ4ESWebXML/VTJ4ES_1008/VTJ4ES-orarend.xml
<?xml version="1.0" encoding="utf-8"?>

<VTJ4ES_orarend 
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="VTJ4ES_orarend.xsd">

    <ora id="1" tipus="elmelet">
        <targy> Számítógép hálózatok </targy>
        <idopont>
            <nap> Hétfő </nap>
            <tol> 08:00 </tol>
            <ig>  09:30 </ig>
        </idopont>
        <helyszin> 032 </helyszin>
        <oktato> dr. Kovács Szilveszter </oktato>
        <szak> Programtervező Informatikus </szak>
    </ora>

    <ora id="2" tipus="elmelet">
        <targy> Mesterséges Intellegencia Alapjai </targy>
        <idopont>
            <nap> Kedd </nap>
            <tol> 10:00 </tol>
            <ig>  11:30 </ig>
        </idopont>
        <helyszin> 033 </helyszin>
        <oktato> Fazekas Levente </oktato>
        <szak> Programtervező Informatikus </szak>
    </ora>

    <ora id="3" tipus="gyakorlat">
        <targy> Mesterséges Intellegencia Alapjai </targy>
        <idopont>
            <nap> Kedd </nap>
            <tol> 12:00 </tol>
            <ig>  13:30 </ig>
        </idopont>
        <helyszin> 033 </helyszin>
        <oktato> Fazekas Levente </oktato>
        <szak> Programtervező Informatikus </szak>
    </ora>
    
    <ora id="4" tipus="elmélet">
        <targy> Adatkezelés XML-ben </targy>
        <idopont>
            <nap> Szerda </nap>
            <tol> 08:00 </tol>
            <ig>  09:30 </ig>
        </idopont>
        <helyszin> A/1 310 </helyszin>
        <oktato> dr. Kovács János </oktato>
        <szak> Programtervező Informatikus </szak>
    </ora>

    <ora id="5" tipus="gyakorlat">
        <targy> Adatkezelés XML-ben </targy>
        <idopont>
            <nap> Szerda </nap>
            <tol> 10:00 </tol>
            <ig>  11:30 </ig>
        </idopont>
        <helyszin> L103 </helyszin>
        <oktato> dr. Bednarik László </oktato>
        <szak> Programtervező Informatikus </szak>
    </ora>

    <ora id="6" tipus="elmelet">
        <targy> Vállalati Információs Rendszerek Fejlesztése </targy>
        <idopont>
            <nap> Szerda </nap>
            <tol> 14:00 </tol>
            <ig>  15:30 </ig>
        </idopont>
        <helyszin> L103 </helyszin>
        <oktato> dr. Sasvári Péter </oktato>
        <szak> Programtervező Informatikus </szak>
    </ora>

    <ora id="7" tipus="gyakorlat">
        <targy> Vállalati Információs Rendszerek Fejlesztése </targy>
        <idopont>
            <nap> Szerda </nap>
            <tol> 18:00 </tol>
            <ig>  19:30 </ig>
        </idopont>
        <helyszin> L103 </helyszin>
        <oktato> dr. Sasvári Péter </oktato>
        <szak> Programtervező Informatikus </szak>
    </ora>

    <ora id="8" tipus="gyakorlat">
        <targy> Számítógépes hálózatok </targy>
        <idopont>
            <nap> Csütörtök </nap>
            <tol> 10:00 </tol>
            <ig>  11:30 </ig>
        </idopont>
        <helyszin> 33 </helyszin>
        <oktato> dr. Kovács Szilveszter </oktato>
        <szak> Programtervező Informatikus </szak>
    </ora>

</VTJ4ES_orarend>
